### PR TITLE
Allow bundle and template paths to be configurable, and compilation is now triggered by whether optimizations are enabled or not.

### PR DESCRIPTION
**Pull request by khalidabuhakmeh**
I created a class called **EmberJs** now, that is basically a static class that users can change the root path to the templates. Also mapping the path no longer depends on HttpContext, which can be fussy at time.

The other change was now the compilation is triggered by whether the user explicitly enables it or not:

```
BundleTable.EnableOptimizations = false; // or true
```

This reduces the view code to this:

```
@Html.RenderEmberTemplates()
@Scripts.Render(EmberJs.BundleNames.App)
```

This shoudl reduce the complexity of getting setup.

If you tell me where I can get the latest compiler.js and what it takes to put it in I can also send you a pull request for that.

### CODE REVIEW

**Comment by Myslik** [comment]
If you compile Ember.js, compiler is in the dist folder.

**Comment by khalidabuhakmeh** [comment]
great, I'll do that and send you another pull request

**Comment by khalidabuhakmeh** [comment]
So I pulled in the latest version of the "compiler" from the handlebars repo and the ember repo. I also am using the built versions of both libraries in the sample.

The thing I am realizing is that this process won't stabilize until the official version 1 of both libraries is released. So I understand how to do this process now, but not sure if this is something you want to publish right now.

If you do publish this assembly, I probably recommend adding the ember.js and handlebar.js files along with the NuGet package so people don't get into js hell.

**Comment by Myslik** [comment]
I am realizing that the best way to compile handlebar templates in Visual Studio would be by VS Extension, but unfortunately I do not know where to begin if I would like to build one. Any ideas?

**Comment by khalidabuhakmeh** [comment]
I personally don't like Visual Studio extensions as part of the compilation process because that means all developers on your team have to have that extension installed. This can block people out of your project inadvertently or ad another layer of frustration.

I like the way you are doing it right now. I just think how the compiler.js gets created needs a better way of being created rather than manually copying and pasting Javascript code. Maybe this won't be so bad once EmberJs freeze on v1.

If you are set on this change, then I can suggest you talk to [Mads Kristensen](https://twitter.com/mkristensen). He is the developer of the Web Essentials Extension. He might possibly add ember compilation support to his extension.

**Comment by Myslik** [comment]
Thanks for point it out. I was inspired by exactly same extension.

I know what you mean, but I would argue that it would be best to deploy the application to production environment with the templates already compiled so you don't have to do it on runtime and save a lot of code in production.

**Comment by khalidabuhakmeh** [comment]
Well the bundler compiles it at app start up, so you only incur the cost of compilation once (per deployment), which most .Net devs are used to at this point.

**Pull request merged**
