### PR TITLE
Updated example to new versions

### PR DESCRIPTION
**Pull request by Globegitter**
Switched to handlebars.runtime
Updated router to APIv2.
Changed .handlebars files to .hbs, just to closer match other ember-projects
Dependencies:
- jQuery to 1.9.1
- Ember to 1.0.0-pre.4 nightly
- handlebars to rc2

### CODE REVIEW

**Comment by Globegitter** [comment]
Hmm, I have been playing a bit more with it and seems that I am getting a really strange error with my pull request now. It says TemplateBuilder() does not exist. Hmm, that is quite annoying and sorry for spamming here so much

**Comment by Globegitter** [comment]
I don't know, this is odd, kinda fixed the bug (by just cloning the rep again and copy+paste replace all the files). But when I update the compiler to 1.1 or 1.2-beta, things don't work anymore. With 1.1 I just get this error in Firebug:  TypeError: n.options.types is undefined
Anyway, this is the last thing I am going to work on it until I get some kind of response, if you have any idea, why things stop working

**Comment by Myslik** [comment]
Hmm, strange I will definitely look into it.

**Comment by Globegitter** [comment]
Cheers, though it is still somehow not working properly when you are trying out the nuget package. I mean I can live with having the project in my solution, but I am just wondering why that is

**Pull request merged**
